### ISSUE TITLE
Disconnected install support

### ISSUE THREAD

**Issue by AmadeusPodvratnik** [IBM/Ansible-OpenShift-Provisioning#143]
Be able to run a disconnected installation of OCP.

**Comment by mohammedzee1000** [comment]
Hi, I will be taking up this issue

**Comment by jacobemery** [comment]
@mohammedzee1000 fantastic! Thank you.

**Comment by mohammedzee1000** [comment]
Also oc-mirror is not currently available for s390x and infact is not a downloadable binary, so we would have to build it from source

```bash
#Install pre-reqs
yum install -y make
dnf install -y gpgme-devel
yum install libassuan-devel


#Install go 1.17
wget https://golang.org/dl/go1.19.10.linux-ppc64le.tar.gz
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.10.linux-ppc64le.tar.gz
export PATH=$PATH:/usr/local/go/bin
go version


git clone https://github.com/openshift/oc-mirror
cd oc-mirror
make build
```

**Comment by mohammedzee1000** [comment]
I read oc mirror documentation where it says clearly it supports 4.10 and above.  So please ignore the operators section in legacy section as it is no longer needed

**Comment by mohammedzee1000** [comment]
Based on some exp with figuring out how to implement this, I have made some minor modifications to the variables. Here is what it looks like now

```yaml
# section 17 - Disconnected ( Optional )
disconnected:
  enabled: True
  registry:
    url: 'host_or_ip:port'
    user: 'user'
    pass: 'password'
    ca_trusted: False
    ca_cert: |
        -----BEGIN CERTIFICATE-----
        Masdinsdiobaewkdsinsdafs... <insert registry certificate>
        -----END CERTIFICATE-----
    pull_secret: '' # this is similar to env.redhat.pull_secret but it will only contain secrets to be applied to the cluster in disconnected mode.
    mirror_pull_secret: '' # this should contain a pull secret that contains the combination of env.redhat.pull_secret and pull secret above for mirroring
  mirroring:
    host: # this is the host that can access the internet as well as the registry
      name: name
      ip: x.x.x.x
      user: root
      pass: pass
    file_server: # in disconnected mode, the client binaries and rhcos will be put on env.file_server and then downloaded to the final destination from there
      clients_dir: ''
      rhcos_dir: ''
      oc_mirror_bin: '' # name of oc-mirror binary in clients_dir. should be a tar.gz file
    legacy:
      platform: True # if true then platform is mirrored in the old way and install config will be patched with the imagecontentsourcepolicy
      ocp_org: 'ocp4'
      ocp_repo: 'openshift4:v4.13.1' #  platform images will be pushed to tegistry_url/ocp_org/ocp_repo
    # this will be implemented in stage 2, this is just data structure
    oc_mirror:
      image_set: # this field is a standard image set from oc-mirror documentation. The only exception is the storageConfig which is altered to allow substitution of disconnected.registry.url
        storageConfig:
          registry:
            enabled: True # use registry storage backend. Currently only supported
            imageURL: # the final value will be {imageURL: disconnected.registry.url/org/repo}
              org: mirror
              repo: oc-mirror-metadata
            skipTLS: false # standard field form oc-mirror schema
        mirror: # this field is also atandard from the oc-mirror schema. It will be substituted as is into the final image set # WARNING: platform mirroring throug oc-mirror is currently not supported, use legacy
          operators:
            - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.13
              full: false
              packages:
              - name: serverless-operator
                channels:
                - name: stable
                  #minVersion: '2.4.1-0'
                  #maxVersion: '2.4.1-0'
          additionalImages:
          - name: registry.redhat.io/ubi8/ubi:latest
          helm: {}
```
